### PR TITLE
Correct OCPN_API_WX32 definition in API-17

### PR DESCRIPTION
**Pull request by bdbcat**

### CODE REVIEW

**Comment by leamas** [comment]
hm... this is really about 7a1d7f146, right -- the rest should not really be part of this ?

**Comment by bdbcat** [comment]
Not sure how they got into the PR.  I just cloned and fetched devel branch.

**Comment by bdbcat** [comment]
Are the other thing not harmless?

**Comment by bdbcat** [comment]
The commit message for that other stuff is:
"sqlite: bugfix (#5)"
Your PR, I think

**Comment by leamas** [comment]
No problem, I can and will cherry-pick the commit from here. Stay tuned.

Not sure about the rest, and very short of time...

**Comment by leamas** [comment]
Done, devel now at 90d5303

**Comment by bdbcat** [comment]
Thanks

**Pull request closed without merging**
