### PR TITLE
Correct another typo

### PR DESCRIPTION
**Pull request by bdbcat**
I do not know what is wrong with this branch.
Please cherry pick the latest commit:
https://github.com/leamas/opencpn-libs/commit/b5775c86d9502bb31da945db251b1f7b08bec7b7
Thanks

### CODE REVIEW

**Comment by leamas** [comment]
Done. devel is now at 7887f6fe82

**Comment by leamas** [comment]
BTW: I presume the  mess comes from not first rebasing on upstream/devel  (upstream if you indeed has named "my" opencpn-libs repo _upstream_)

**Comment by bdbcat** [comment]
I used the github "sync" button, from my repo, on this branch.  Doesn't work?

**Comment by leamas** [comment]
seemingly not...

**Pull request closed without merging**
