### PR TITLE
Add the marnav library

### PR DESCRIPTION
**Pull request by nohal**
- Uses git submodule, the plugins using it should update the CI scripts to use recursive checkout

### CODE REVIEW

**Comment by leamas** [comment]
I have missed this... but not now. BBL

**Comment by leamas** [comment]
hm... If possible, we should avoid a recursive submodule. I have had serious problems making this submodule accepted by Mike and others, and adding a recursive  layer might be problematic.

The alternative would be  a somewhat more complex CMakeLists which downloads sources when included. This keeps the library small until actually used. Do you see any drawbacks with such an approach?

**Comment by nohal** [comment]
Will it work in the flatpak build, where we can't download anything at build time (which is the reason this PR exists)?
I don't see any reason a submodule should be a problem here for a newly added library, whoever will want to use it will simply learn how submodules work.

**Comment by leamas** [comment]
No, it will not. For flatpak we have the snippets in opencn-libs/flatpak.  

Basically, flatpak cannot download anything at build time. OTOH, it has the modules concept, modules are basically dependencies rebuilt at  compile time.  They must eventually be part of the single yaml manifest used when building.

Shipdriver has code which copies snippets form .../flatpak into the manifest before it's used. Look into *cmake/ConfigureManifest.cmake*  for a hopefully clarifying comment. shipdriver's *flatpak/org.opencpn.OpenCPN.Plugin.shipdriver.yaml* has some examples.

**Comment by nohal** [comment]
Hmmm... I still don't see any real reason not to use a git submodule here and switch to a more complicated (for me) workflow, this PR has zero potential to break anything that exists.

**Comment by leamas** [comment]
OK, let me rewrite it in a day or two, I have done these things before and it's not complicated for me. Stay tuned...

**Comment by leamas** [comment]
Hm.. have you an example plugin which needs this which I can tinker with?

EDIT: just to clarify: That it doesn't work for Flatpak it's not some idea of mine, it's  a hard policy limitation in flatpak-builder.

**Comment by nohal** [comment]
https://github.com/nohal/nsk_pi
Yes, I understand that it is the flatpak policy, but this repository is the solution we are using for it and I really don't see why it should not be using submodules where appropriate and making a copy of the source is not necessary.

**Comment by leamas** [comment]
Pushed a new commit 781eef3 to devel.  I'm not confident with this, have a bad feeling there are better solutions. Furhermore, circleci is down so I cannot verify that it builds on all platforms. Have verified Flatpak  and, FWIW, Fedora 38.

To use this one needs to add a line in the Flatpak  manifest which lives in the flatpak/ directory. Excerpt from my testing
```
modules:
    - @include opencpn-libs/flatpak/glu.yaml
    - @include opencpn-libs/flatpak/marnav.yaml
```

Otherwise, it's used as any library in Plugin.cmake:
```
  add_subdirectory("${CMAKE_SOURCE_DIR}/libs/marnav")
  target_link_libraries(${PACKAGE_NAME} ocpn::marnav)
```

**Comment by leamas** [comment]
>  and making a copy of the source is not necessary.

Agreed, we should not do that and my commit doesn't.

It turns out that this was more complicated than I thought, including a library in the configuration this way is something new..

There are build errors in the marnav library in the recent Bookworm build [here](https://circleci.com/api/v1.1/project/github/leamas/shipdriver_pi/18785/output/102/0?file=true&allocation-id=640cf5afbb86a3743e606c42-0-build%2FX2979SH4)

Looks lke some new compiler checks.

**Comment by nohal** [comment]
This has already been fixed after https://github.com/mariokonrad/marnav/issues/52, but only in master for now, not in 0.14.0 included in your commit.

**Comment by leamas** [comment]
OK, updated to use latest master in ca7b53d8. As said in commit  it would have been cleaner to apply a patch, but lazy now. 

Might update later.

**Comment by leamas** [comment]
@nohal : Let me know if this is OK for you in which case we could close this one

**Comment by leamas** [comment]
wait... Finally found your nsk_pi, sorry for missing it. Working on it, have the basic marnav lib in place but there are other issues. stay tuned.

**Pull request closed without merging**
